# Generated by Django 6.0.5 on 2026-05-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ["name"],
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ["title"],
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "ordering": ["ingredient__name"],
                "verbose_name": "Ингредиент рецепта",
                "verbose_name_plural": "Ингредиенты рецепта",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("g", "г"),
                    ("kg", "кг"),
                    ("ml", "мл"),
                    ("l", "л"),
                    ("piece", "шт"),
                    ("tbsp", "ст. л."),
                    ("tsp", "ч. л."),
                    ("pinch", "щепотка"),
                ],
                max_length=20,
            ),
        ),
    ]
